export const FETCHING_KAMAR = 'FETCHING_KAMAR';
export const FETCHING_KOST = 'FETCHING_KOST';
export const LOGIN_USER = 'LOGIN_USER';
export const LOAD_SESSION = 'LOAD_SESSION';
export const SIGNUP = 'SIGNUP';
export const LOGOUT = 'LOGOUT';

// export const LOGIN_ADMIN = "LOGIN_ADMIN";

// export const ONCHANGE_LOGIN = "ONCHANGE_LOGIN";
// export const FETCHING_ACCOUNT = "FETCHING_ACCOUNT";
// export const FETCHING_ACCOUNT_SUCCESS = "FETCHING_ACCOUNT_SUCCESS";
// export const FETCHING_ACCOUNT_FAIL = "FETCHING_ACCOUNT_FAIL";
